name: Build Container Images as Anonymous
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Scripts
        run: shellcheck build-*.sh
      - name: Run Scripts
        run: |
          ./build-tools.sh latest